/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jiangxiujie_androidjni_JniMain */

#ifndef _Included_com_example_jiangxiujie_androidjni_JniMain
#define _Included_com_example_jiangxiujie_androidjni_JniMain
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_jiangxiujie_androidjni_JniMain
 * Method:    helloJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_jiangxiujie_androidjni_JniMain_helloJni
  (JNIEnv *, jclass);

/*
 * Class:     com_example_jiangxiujie_androidjni_JniMain
 * Method:    addCalc
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_jiangxiujie_androidjni_JniMain_addCalc
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
